### ISSUE TITLE
Database Models specification

### ISSUE THREAD

**Issue by ahmedmgamal** [development-data-intelligence/DDCave#4]
This issue is meant to work as an `Epic` for CAVE database model stories.

# Description

CAVE intends to store data of `Team`, `Application`, `Endpoint`, `File` level metrics, allowing its users to `track`, `link`, `measure` and `visualise` the status of their organisation.

To enable this, CAVE needs to be able to have well defined structures that store this information.

CAVE requires a `User Model` such that users can register and interact with cave as well
at the granularity their allowed to see their own metrics.

CAVE requires `Permission Model` such that is easy to determined what is visible to what individual.

CAVE requires a ` User Group/Organisation Model` such that is easy to identify groups of users with same access to the datasets.

CAVE requires a `Metric Record Model` such that user registered metrics can be validated an accurately tracked.

CAVE requires a `Data Point Model` such that every entry can be related to e Metric Record and correlations can be easily made with the data.

# To close this issue - Acceptance Criteria
- [ ] There is a clear `User Story` and `Github Issue` created for each Model.
- [ ] User Model is defined
- [ ] Permission Model is defined
- [ ] User Group/Organisation Model is defined
- [ ] Metric Record Model is defined
- [ ] Data Point Model is defined
