### ISSUE TITLE
UI/UX specification

### ISSUE THREAD

**Issue by ahmedmgamal** [development-data-intelligence/DDCave#5]
This issue is meant to work as an `Epic` for CAVE User Interface stories.

# Description
Cave needs to provide a place where a User can interact with cave without having
to dive into technical details. `Consumer` of data Collated in Cave. As such this issue goal
is to gather requirements of what that User Experience should look like.

# To close this issue - Acceptance Criteria 
- [ ] A finite number of pages/core functionality is defined.
- [ ] There is a clear `User Story` and `Github Issue` created for each page.
- [ ] Web Stack is defined.
